FROM flux-build:latest AS builder

COPY --chown=builder:builder . /home/builder/src

WORKDIR /home/builder/src

RUN go get github.com/influxdata/pkg-config

RUN go build ./cmd/flux

FROM golang:1.16

COPY --from=builder /home/builder/src/flux /go/flux

CMD ["/go/flux", "repl"]
